// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rkgeoksdensgqvuednyd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJrZ2Vva3NkZW5zZ3F2dWVkbnlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc1NTYxMDYsImV4cCI6MjA1MzEzMjEwNn0.83SJG7O-3JkDswHeU0iZKadu968vJTVIjHFlA3-GNv8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);